# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08fc831372859c6306981052c07099131b2a1c0f58c57a8cb654c30d1e53dcd6194dfcf7f168e793e0aacaf6c2387e96fe75c08a483ff2562ba8c19561b75b4b

test:
  secret_key_base: 83c47ac64ba42bd9242c9bf87844083245167cef06f3edf290d1123e52fe461e161b8f373745d44950401e1e5a05e38991638954eba378fc017fe6fe5fba6bd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
